# Rules for compiling and showing the PDF from the LaTeX sources

# Input files
TEX = $(wildcard *.tex)
# Output files
PDF = $(patsubst %.tex,%.pdf,$(TEX))

# Generate all PDFs
all: $(PDF)

# Generate a PDF from a Tex file
%.pdf: %.tex
	tectonic -X compile $<

# Clean the temporary files generated by the tex programs (including the PDFs)
clean:
	rm -f $(PDF)
