name: pdf-compile

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup caching for tectonic
        uses: actions/cache@v2
        with:
          path: ~/.cache/Tectonic
          key: tectonic-${{ runner.os }}

      - name: Setup caching for conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          environment-file: environment.yml
          activate-environment: cv
          miniforge-variant: Mambaforge
          miniforge-version: "latest"
          use-mamba: true
          channel-priority: strict
          use-only-tar-bz2: true

      - name: Compile the PDF
        run: make

      - name: Send PDF to server
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "leighton_payne_cv.pdf"
          target: "${{ secrets.REMOTE_DIR }}"
